name: 'Antithesis Trigger Action'
description: 'An action that triggers an Antithesis workflow'
author: 'AntithesisHQ'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  notebook_name:
    description: 'The name of the notebook containing the workflow to run'
    required: true
    default: 'demo_ci_integration_webhook'

# Define your outputs here.
outputs:
  result:
    description: 'Whether triggering the workflow was successful or not'

runs:
  using: node20
  main: dist/index.js
