name: 'Antithesis Trigger Action'
description: 'An action that triggers an Antithesis workflow'
author: 'AntithesisHQ'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'purple'

# Define your inputs here.
inputs:
  notebook_name:
    description: 'The name of the notebook containing the workflow to run'
    required: true
    default: 'demo_ci_integration_webhook'
  tenant:
    description: 'The name of the tenant'
    required: true
    default: ''
  username:
    description: 'The username of the account running the workflow'
    required: true
    default: ''
  password:
    description: 'The password of the account running the workflow'
    required: true
    default: ''
  github_token:
    description: 'The Github token to be used to post back status updates'
    required: true
    default: ''
  images:
    description: 'The containers & digests that Antithesis tests will run on. If not specified the values will be inferred from the test.'
    required: false
    default: ''

# Define your outputs here.
outputs:
  result:
    description: 'Whether triggering the workflow was successful or not'

runs:
  using: node20
  main: dist/index.js
