name: 'Antithesis Trigger Action'
description: 'An action that triggers an Antithesis workflow'
author: 'AntithesisHQ'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'purple'

# Define your inputs here.
inputs:
  notebook_name:
    description: 'The name of the notebook containing the workflow to run'
    required: true
    default: 'demo_ci_integration_webhook'
  tenant:
    description: 'The name of the tenant'
    required: true
    default: ''
  username:
    description: 'The username of the account running the workflow'
    required: true
    default: ''
  password:
    description: 'The password of the account running the workflow'
    required: true
    default: ''
  github_token:
    description: 'The Github token to be used to post back status updates'
    required: true
    default: ''
  config_image:
    description:
      'The image version that Antithesis will pull from the container registry
      for the config image.'
    required: false
    default: ''
  images:
    description:
      'The containers & digests that Antithesis tests will run on. If not
      specified the values will be inferred from the test.'
    required: false
    default: ''
  description:
    description: 'A string description of your test run.'
    required: false
    default: ''
  team:
    description:
      'A string naming the team/group to which the person that invoked this run
      belongs.'
    required: false
    default: ''
  system_name:
    description:
      "A string encoding a readable, version-irrespective name for the system
      you're testing."
    required: false
    default: ''
  test_name:
    description:
      'A string representing the test name being run. This is required when
      running multiple tests from the same commit.'
    required: false
    default: ''
  email_recipients:
    description:
      'A semicolon-delimited list of the email addresses for the recipients who
      will be emailed links to the triage report produced by this test run. If
      this parameter is not specified, emails will be sent to the default users
      set up for the test.'
    required: false
    default: ''
  additional_parameters:
    description:
      'A newline-separated list of additional parameters to be sent to the test
      run.'
    required: false
    default: ''

# Define your outputs here.
outputs:
  result:
    description: 'Whether triggering the workflow was successful or not'

runs:
  using: node20
  main: dist/index.js
